FROM node:12.16.1-alpine As builder

WORKDIR /yoni/projetBuffa_assignments/web/src/app

COPY package.json package-lock.json ./

RUN npm install

COPY . .

RUN npm run build --prod

FROM nginx:1.15.8-alpine

COPY --from=builder /yoni/projetBuffa_assignments/web/src/app/dist/assignment-app/ /usr/share/nginx/html
